hosts: localhost
parallelism: false

tasks:
  - name: Leer configuraci√≥n de Apache sin comentarios
    module: file_read
    args:
      path: "/etc/apache2/apache2.conf"
      grep: "^[^#]"
      become: true
